// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChbfnGM9qWnZ-hwSCqrW5mFx0bq0bEwlQ',
    appId: '1:810990561058:web:aece397464458cdbd9e77b',
    messagingSenderId: '810990561058',
    projectId: 'trprosp',
    authDomain: 'trprosp.firebaseapp.com',
    storageBucket: 'trprosp.firebasestorage.app',
    measurementId: 'G-R11WV39YNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4BELs4nVVwxbhv2d0s6uOOyJtK092Dus',
    appId: '1:810990561058:android:6d2ead5971c560bdd9e77b',
    messagingSenderId: '810990561058',
    projectId: 'trprosp',
    storageBucket: 'trprosp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrzdTnDsS3hpa-kfuHubtTQ7gMg0SVsQ',
    appId: '1:810990561058:ios:46cfc008ca6bd20ad9e77b',
    messagingSenderId: '810990561058',
    projectId: 'trprosp',
    storageBucket: 'trprosp.firebasestorage.app',
    iosBundleId: 'com.example.prospapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrzdTnDsS3hpa-kfuHubtTQ7gMg0SVsQ',
    appId: '1:810990561058:ios:46cfc008ca6bd20ad9e77b',
    messagingSenderId: '810990561058',
    projectId: 'trprosp',
    storageBucket: 'trprosp.firebasestorage.app',
    iosBundleId: 'com.example.prospapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChbfnGM9qWnZ-hwSCqrW5mFx0bq0bEwlQ',
    appId: '1:810990561058:web:50fd3e40327766ebd9e77b',
    messagingSenderId: '810990561058',
    projectId: 'trprosp',
    authDomain: 'trprosp.firebaseapp.com',
    storageBucket: 'trprosp.firebasestorage.app',
    measurementId: 'G-DL7CG7HQ7V',
  );
}
